combine:
  root: '/home/jnan1/repos/FlowVerify/'
  gmu_test:
    gt_json: 'pipeline/gen/gt/GMU_TEST_1.json'
    dt_json: 'pipeline/gen/dt/TDID_GMU_TEST1.json'
    run_dir: 'pipeline/gen/score_files/all_gmu'
    catIds: [5, 10, 12, 14, 18, 21, 28, 50, 79, 94, 96]
    config: 'pipeline/configs/tdid_gmu_test.yaml'

  rgbd:
    gt_json: 'pipeline/gen/gt/WRGBD_GT.json'
    dt_json: 'pipeline/gen/dt/TDID_RGBD_OUT_030.json'
    run_dir: 'pipeline/gen/score_files/all_rgbd'
    catIds: [1004, 1005, 1007, 1053, 1055, 1050, 1052, 1054, 1252]
    config: 'pipeline/configs/tdid_rgbd.yaml'
      
  scorers:
    FlowVerify:
      score_names: ['FRigid', 'FColor', 'FPrec', 'FRec', 'SimObj_0.5']
      params: [0.9, 0.5, 0.9, 0.3, 0.0]
    Detector:
      score_names: None
      params: None
    SiftVerify:
      score_names: ['SMatches', 'SPrecision']
      params: [0.1, 0.9]

  flownet:
    model_path: '/home/jnan1/models/oneshot_bigbird_ckpt_1650500.pth'
